project_id = "jndociyjhmlgrvqetdzy"

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.log-login]
verify_jwt = false

[functions.lookup-user-email]
verify_jwt = false

[functions.send-doctor-notification]
verify_jwt = false

[functions.create-demo-user]
verify_jwt = false
